### PR TITLE
Document system tables

### PR DESCRIPTION
**Pull request by sagivf**
Added some documentation to try and build a mental model of queries and API.

### CODE REVIEW

**Comment by sagivf** [comment]
@oferitz I've dug into the system tables a little more and I think we should do away with the "stats" queries.
Seems to me a lot cleaner to split queries to cluster, servers, db, servers, tables.
The stats can be added to the query getting the info regarding each entity or as a separate query but I think they should sit next to each other and not in a dedicated "stats" file.
What do you think?

**Comment by oferitz** [comment]
@sagivf You are referring to the "queries" part, right? We will still need a stats Model that aggregate all those separated queries.

**Comment by sagivf** [comment]
I'm not sure, why not just hold a live queries for "tables", "servers", "cluster", "db".
The aggregations would be in the "cluster" queries or maybe event just on client. 
I think the "stats" can just sit along with the other data of each entity,
If there where just one place for stats that would be ok, but since it's all over the app in different constellations I don't see a use for a specific "stats" entity.

**Comment by oferitz** [comment]
Sounds reasonable, but i will love to see working example in order to understand better how it's done.

**Pull request merged**
