### PR TITLE
Add Standard.JS resolve #12.

### LINKED ISSUE #12: StandardJS
Set up standard.js as linter. we need to make sure it works nicely with Prettier (might require some non-trivial settings)

### PR DESCRIPTION
**Pull request by grandquista**
This is an initial commit for integrating Standard.JS into the build process. I haven't included any lint changes in this yet because they touch a large number of lines fixing indentation and quoting. Prettier does not seem to be loading its config file currently. This will be fixed in this PR to get a consensus for lint changes. I can also add pre-commit hooks for both linters here.

### CODE REVIEW

**Comment by oferitz** [comment]
Thanks. Currently the `test-all` script is not implemented i just put their as placeholder so you might want to move the standard command to `test` which is working.
I'm not sure that i understood, does this PR makes Prettier not working now?

**Comment by grandquista** [comment]
This PR doesn't do anything with Prettier. I just noted that running Prettier with `test-all` does not make use of the config file.

**Comment by grandquista** [comment]
There are two unused imports that don't have an obvious current use. I can comment those, or add a one line use, or wait for the features to be written before rebaseing this.

**Comment by oferitz** [comment]
You can comment the unused imports for now but there is other issue, Standard should not determine any styling rules like indentation and quoting, this is Prettier responsibility, Standard should only serve as a JS linter. The current setup of Standard will conflict with Prettier. 
For example:

 `{type = '', size = 24, color = '#000', className = 'rebirth-icon'}` - the spacing around equal sign will be reformatted by Prettier.

`<Icon type='error' size={96} />` - in JSX props should be with double quotes.

I think we got 3 options here:
1. Configure Standard to be linter only i.e report unused imports, global vars, using var, etc.
2. In NPM scripts always run Standard first followed by Prettier.
3. Just using Prettier if setting both of them is a hassle.

What do you think?

**Comment by gjuchault** [comment]
@oferitz I like this idea, many people do this indeed. Standard/eslint the code to check for errors, keep prettier for style

I've been using prettier only, it's already very nice (prettier + husky + lint-staged)

**Comment by oferitz** [comment]
@gjuchault Yeah looks like it's common practice: https://github.com/sheerun/prettier-standard

**Comment by grandquista** [comment]
Option 1 is out.

> Configure Standard to be linter only i.e report unused imports, global vars, using var, etc.

https://standardjs.com has it at the top of their page that there is no configuration.

https://github.com/sheerun/prettier-standard is a different approach using eslint configured to act according to the StandardJS rules. I don't see anything that indicates they are using Standard itself.

I can work on a new PR with a different linter if this isn't the direction intended.

**Comment by oferitz** [comment]
What about option 2? I know it's a bit strange setup (double formatting) but it could work.

**Comment by grandquista** [comment]
Here is what rebasing and double formatting looks like.

**Comment by oferitz** [comment]
@grandquista Thanks for putting the effort! we can start with that and see if it works well for us. i Am going to merge and close.

**Pull request merged**
